### ISSUE TITLE
bcolz.empty

### ISSUE THREAD

**Issue by mrocklin** [Blosc/bcolz#111]
We have `bcolz.ones` and `bcolz.zeros` but no `bcolz.empty`.  If I want to create a large bcolz carray of a datetime or string dtype what is the best way?

Is there a way to do this for record dtypes and ctable as well?

**Comment by FrancescAlted** [comment]
No, bcolz.empty has not much sense in bcolz because bcolz.zeros compress the best.  Regarding the question of creating a large array, it is generally best to use bcolz.fromiter because you reduce the number of updates, which is a costly operation (the complete chunk needs to decompress/compress).

BTW, I think is much better to use the mailing list for this sort of questions because more people can chime in before.
