### ISSUE TITLE
Question on bcolz to numpy array conversion performance

### ISSUE THREAD

**Issue by monkeybutter** [Blosc/bcolz#265]
I've being doing some benchmarks comparing different serialization formats and how fast we can read from disk. The comparison includes numpy's fromfile, hdf5 and bcolz:

https://gist.github.com/monkeybutter/ed72220be48333ce0dde

bcolz is amazingly fast at reading the file and creating the carray object, one order of magnitude faster than the second best, h5py. However, I would like to understand why the conversion of a bcolz into a numpy array is so expensive (gist cell no. 8)

I know bcolz is intended to be used to perform operations internally using the functionality it exposes, but to be fair with the benchmark I wanted to do the comparison using the same numpy array as the output for all the cases.

Is there anything that can be done to improve the speed of this conversion?

**Comment by FrancescElies** [comment]
Hi,

In the case of cell nr 8 your chunks of data need to travel from disk to memory and decompressed into a numpy array, that's the reason for the extra time needed.

In cell 8, you could try to play with compression level (from 1 to 9, being 9 de maximum compression level) and see which are the effects.
``` python
# cell 8
with bcolz.carray(arr1, rootdir='data/bcolz', mode='w', cparams=bcolz.cparams(clevel=1)) as _:  
    c = _  

%time arr7 = load_bcolz("'data/bcolz'")[:, :]

```
I noticed you were playing around with different compression algorithms in the h5 case. 
Bcolz uses blosc, offering you many compression algorithms like `blosclz, lz4, lz4hc, snappy, zlib`, you could try them in combination with different compression level to see if you get any speed boost
``` python
# cell 8
# clevels = range(1,10)
# cnames = ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib']

with bcolz.carray(arr1, rootdir='data/bcolz', mode='w', cparams=bcolz.cparams(clevel=clevel, cname=cname)) as _:  
    c = _  

%time arr7 = load_bcolz("'data/bcolz'")[:, :]

```

I'm not sure if is there a faster way of getting your numpy array rather than using `[:]`

**Comment by FrancescElies** [comment]
I forgot to mention you could also pass expected length as a parameter https://bcolz.readthedocs.org/en/latest/opt-tips.html#informing-about-the-length-of-your-carrays, though I'm not sure if `bcolz.carray` already uses the length of the array to calculate the chunk length internally.

Once you are fine tunning you could try out to the deactivate the shuffle filter, but maybe your compression ratio will be worse int that case https://bcolz.readthedocs.org/en/latest/tutorial.html#compression-level-and-shuffle-filter

**Comment by monkeybutter** [comment]
Thanks @FrancescElies, I will do some comparisons between compressors, levels and chunk lenghts.

My point was more about understanding how bcolz is mapping data into memory and how close is that to a numpy array. Comparing blosc with what other libraries do (using my dataset), it looks like loading the blosc object from disk is done in 4ms but the transformation to a numpy array takes 40ms. Other libraries like h5py read from disk and return a numpy array in 20ms. This difference makes me wonder if maybe the hdf5 data representation is closer to a numpy array than the one used by bcolz, or there might be other reasons.

**Comment by FrancescElies** [comment]
When you read bcolz object from disk, your data is actually not loaded to memory except the leftovers which are actually loaded into memory as a numpy array, that's why it is so fast to open an on-disk carray.

If you have a look at the memory consumed by `arr7 = load_bcolz("'data/bcolz'")` you will see is way much less than your compressed data, this is because your data is still on disk, only loaded when needed, let's say for example when you [:] or [1] or maybe use an iterator.

I believe `clevel = 1 ` should give you nice speeds but compress ratio will be worse

**Comment by FrancescAlted** [comment]
@monkeybutter, most of the comments by @FrancescElies are correct, but I think you are not comparing pears with pears here.  The thing that takes 20 ms in h5py is reading a contiguous, non-compressed HDF5 array.  This is fast.  But the chunked and compressed version of the array is in cells 5 and 6 (with a different chunksize): this is what is comparable with bcolz (the storage is chunked and compressed by default).  In the case, the speed of bcolz is almost ~2x faster than h5py (~80 ms vs ~40 ms), and this is the expected figure.  Of course, I don't think this is due to differences in peformance of HDF5 vs bcolz, but rather just due to Blosc performance.  For example, PyTables can use HDF5 in combination with Blosc, and I would predict that performance would be similar than bcolz in this case.

As @FrancescElies pointed out, you can play with tuning several knobs in bcolz for getting more performance (using different compression levels, different internal compressors, different number of threads, different chunk lengths, and so on and so forth).  But it is important to remember that you are probably using a misleading comparison because probably your data is already in the cache of your OS (which is my guess for the scenario in your benchmark).  However, and because both lzf and Blosc are very fast in comparison with hard disks, when you are reading *from disk* you will end having speed-ups that are very close to the compression ratio (in our example above, if the compression ratio is ~2x, then your expected speed-up would be ~2x roughly too).  With SSDs things may be different and Blosc might start to show some noticeable advantage wrt other compressors (e.g. lzf).  For in-memory decompressions (i.e. your likely scenario above) Blosc should have a *clear* advantage in general.

Finally, bcolz is meant to store data compressed either in-memory or on-disk, and that means that you can squeeze the most of it when you operate its containers (carray, ctable) either using [iterators](https://bcolz.readthedocs.org/en/latest/reference.html#iter) or [block-iterators](https://bcolz.readthedocs.org/en/latest/reference.html#iterblocks), or using blocked algorithms via [eval](https://bcolz.readthedocs.org/en/latest/reference.html#eval) or just via external packages like [bquery](https://github.com/visualfabriq/bquery) or [dask](https://github.com/blaze/dask).

Sorry for the extension of the message but as you see benchmarking I/O is a complex (and sometimes very mysterious) task, with lots of parameters to have in account.  But the rule of thumb is: experiment with your own data and decide by yourself.

**Comment by FrancescElies** [comment]
@FrancescAlted don't feel guilty about correcting any none sense I might write ;-)

**Comment by monkeybutter** [comment]
Thank you both @FrancescElies and @FrancescAlted for all the information you have shared. I find really interesting knowing more about the internals of blosc and understanding what is really happening under the hood.

Reading your comments I've realised the results will be highly dependent on the data, machine architecture and all the internal tuning parameters of bcolz. Finding the sweet spot would require traversing these parameters in every dimension [compressor, clevel, chunk size, concurrency, ...] for any particular data set and machine.

I understand I'm mixing pears and apples in my benchmark trying to compare contiguous non compressed arrays with blocked compressed arrays. Knowing they are different kinds of fruit, I had the idea that reading from disk, blocked compressed arrays could beat, in some cases, non compressed contiguous arrays . If the data happens to be highly compressible [and shuffleble :-) ] and the chunk size matches the cache size of the CPU, is it possible to beat plain disk contiguous arrays?

**Comment by FrancescAlted** [comment]
Yep, as said, for hard disk I/O, using (fast) compression normally beats non-compression quite easily.  For SSDs it depends on how fast is the disk wrt CPU speed (and also the dataset).  For in-memory, although compression normally does not beat non-compression, there are some (real-life) situations where this is already the case:

 https://github.com/Blosc/movielens-bench/blob/master/querying-assp14.ipynb

[the specs for the 'Big Iron' machine can be seen [here](https://python.g-node.org/python-summerschool-2014/starving_cpu)]

My prediction is that compression will beat non-compression in more and more scenarios as time goes by.
