### ISSUE TITLE
Should bcolz meet Apache Arrow/feather?

### ISSUE THREAD

**Issue by kzk2000** [Blosc/bcolz#300]
This is more of a pointer to something that might be of interest to low-level blosc/bcolz developers:
http://www.r-bloggers.com/feather-a-fast-on-disk-format-for-data-frames-for-r-and-python-powered-by-apache-arrow/

It seems to me that blosc/bcolz would be very well suited for the project Wes McKinney and Hadley Wickham have been up to lately. Not sure if those two are even aware of what bcolz has to offer...

**Comment by FrancescAlted** [comment]
Nice article, thanks for sharing.  Indeed, after a fast glance over it, it seems like bcolz and Feather are sharing quite a bit of goals.  I'd say that bcolz is completely attached to Python, whereas Feather, being written in C++, is a more general approach.  On the other hand, compression is extremely important for bcolz since the very beginning, whereas it seems a secondary goal for Feather.  And I am pretty sure Wes knows about bcolz, but he should have considered it was not appropriate for their goals.

All in all, it is good to see others seeing the potential of using SSDs as a replacement of memory.
